'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { accuracyReasons, countWords, overviewItems, type OverviewItem } from '@/lib/task1-overview/cases';
import styles from './Task1Overview.module.css';

type Phase='start'|'select'|'evidence'|'accuracy'|'review'|'draft'|'revise'|'result';
type Attempt={selected:number[];overview:string;evidence:Record<number,number>;reasons:Record<number,number>;correction:string};
const revisionFocus=['Главное и точность данных','Порядок и связи между абзацами','Точность слов для изменения и сравнения','Грамматика и формы слов'];
function updateChoice(previous:Record<number,number>,index:number,value:string){const next={...previous};if(value==='')delete next[index];else next[index]=Number(value);return next;}

function Chart({item}:{item:OverviewItem}) {
  const max=Math.ceil(Math.max(...item.series.flatMap((series)=>series.values))/20)*20;
  return <figure className={styles.chart}><figcaption><strong lang="en">{item.title}</strong><span>{item.unit}</span></figcaption><svg viewBox="0 0 540 340" role="img" aria-label={`Линейный график: ${item.title}. Точные значения доступны в таблице под графиком.`}>
    {[0,1,2,3,4].map((tick)=><g key={tick}><line x1="60" x2="510" y1={280-tick*60} y2={280-tick*60} className={styles.gridLine}/><text x="48" y={285-tick*60} textAnchor="end">{max*tick/4}</text></g>)}
    {item.years.map((year,index)=><text key={year} x={70+index*140} y="310" textAnchor="middle">{year}</text>)}
    {item.series.map((series,index)=><g key={series.name} className={[styles.seriesA,styles.seriesB,styles.seriesC][index]}><polyline points={series.values.map((value,point)=>`${70+point*140},${280-value/max*240}`).join(' ')} fill="none" strokeWidth="3" strokeDasharray={index===1?'8 5':index===2?'3 4':undefined}/>{series.values.map((value,point)=><circle key={point} cx={70+point*140} cy={280-value/max*240} r="5"/>)}</g>)}
  </svg><ul className={styles.legend}>{item.series.map((series,index)=><li key={series.name}><span className={[styles.seriesA,styles.seriesB,styles.seriesC][index]} aria-hidden="true">{index===0?'━':index===1?'┄':'┈'}</span>{series.name}</li>)}</ul><details><summary>Точные значения таблицей</summary><table><caption>{item.unit}</caption><thead><tr><th scope="col">Series</th>{item.years.map((year)=><th key={year} scope="col">{year}</th>)}</tr></thead><tbody>{item.series.map((series)=><tr key={series.name}><th scope="row">{series.name}</th>{series.values.map((value,index)=><td key={index}>{value}</td>)}</tr>)}</tbody></table></details><p className={styles.note}>Точки — записанные значения. Линии соединяют их для удобства; график не показывает причины изменений.</p></figure>;
}

export default function Task1Overview(){
  const [round,setRound]=useState(0);
  const [phase,setPhase]=useState<Phase>('start');
  const [selected,setSelected]=useState<number[]>([]);
  const [overview,setOverview]=useState('');
  const [evidence,setEvidence]=useState<Record<number,number>>({});
  const [reasons,setReasons]=useState<Record<number,number>>({});
  const [correction,setCorrection]=useState('');
  const [first,setFirst]=useState<Attempt|null>(null);
  const [transfer,setTransfer]=useState<Attempt|null>(null);
  const [draft,setDraft]=useState('');
  const [revision,setRevision]=useState('');
  const [focus,setFocus]=useState('');
  const [noChanges,setNoChanges]=useState(false);
  const [error,setError]=useState('');
  const item=overviewItems[round];
  const order=round===0?[0,3,1,5,2,4]:[5,2,4,0,3,1];
  useEffect(()=>{if(phase!=='start'){const heading=document.getElementById('overview-stage-title');heading?.scrollIntoView({block:'start'});heading?.focus({preventScroll:true});}},[phase,round]);
  function advance(next:Phase){setError('');setPhase(next);}
  function begin(){setRound(0);setSelected([]);setOverview('');setEvidence({});setReasons({});setCorrection('');setFirst(null);setTransfer(null);setDraft('');setRevision('');setFocus('');setNoChanges(false);advance('select');}
  function commitSelection(){if(selected.length!==3||!overview.trim()){setError('Выбери ровно три главных утверждения и напиши свой overview.');return;}advance('evidence');}
  function commitEvidence(){if(selected.some((index)=>evidence[index]===undefined)){setError('Для каждого выбранного утверждения укажи опору или отсутствие подтверждения.');return;}advance('accuracy');}
  function commitAccuracy(){if(item.inaccurate.some((_entry,index)=>reasons[index]===undefined)||!correction.trim()){setError('Оцени каждое предложение и напиши свой исправленный абзац.');return;}const attempt={selected:[...selected],overview,evidence:{...evidence},reasons:{...reasons},correction};if(round===0)setFirst(attempt);else setTransfer(attempt);advance('review');}
  function startTransfer(){setRound(1);setSelected([]);setOverview('');setEvidence({});setReasons({});setCorrection('');advance('select');}
  function report(attempt:Attempt,source:OverviewItem){
    const mainCount=attempt.selected.filter((index)=>source.claims[index].main).length;
    return <div className={styles.review}><div className={styles.summary}><p><strong>{mainCount} из 3</strong> выбранных утверждений подходят для главного обзора.</p><p><strong>{attempt.selected.filter((index)=>attempt.evidence[index]===source.claims[index].evidence).length} из 3</strong> опор совпали с разбором.</p><p><strong>{source.inaccurate.filter((entry,index)=>attempt.reasons[index]===entry.reason).length} из 3</strong> типов неточности совпали.</p></div>{mainCount<3&&<p className={styles.warning}>Отдельный верный факт может быть лишней деталью для overview. Неподтверждённое утверждение нужно удалить, даже если ты правильно отметил отсутствие опоры.</p>}<h3>Какие особенности важнее всего?</h3>{source.claims.map((claim,index)=><div className={styles.feedbackRow} key={index}><strong lang="en">{claim.text}</strong><p>{claim.main?'Главное для обзора':'Не выбираем для обзора'} · {claim.explanation}</p><p className={styles.note}>{attempt.selected.includes(index)?`Ты выбрал это утверждение. Опора: ${source.evidence[attempt.evidence[index]]}`:'Ты не выбирал это утверждение.'}</p></div>)}<div className={styles.compare}><div><h3>Твой overview до разбора</h3><p lang="en">{attempt.overview}</p></div><div><h3>Один возможный overview</h3><p lang="en">{source.modelOverview}</p></div></div><p className={styles.note}>Свободный текст не проверен автоматически. Сравни, описывает ли твой overview главные тренды и ранги, и убери причины, которых нет на графике. Возможны другие точные формулировки.</p><h3>Исправление неточного абзаца</h3><p className={styles.saved} lang="en">{attempt.correction}</p>{source.inaccurate.map((entry,index)=><div className={styles.feedbackRow} key={index}><p lang="en">{entry.text}</p><strong>{accuracyReasons[entry.reason]}</strong><p lang="en">{entry.correction}</p></div>)}</div>;
  }
  return <main className={styles.page}><div className={styles.topline}><Link href="/trainers">← Все тренажёры</Link><span>ASHYQ · TASK 1 LAB</span></div><header className={styles.hero}><p className={styles.eyebrow}>IELTS ACADEMIC · WRITING TASK 1</p><h1>Сначала главное. Потом текст.</h1><p>Выбери основные особенности графика, напиши overview и проверь каждое утверждение по данным. Затем собери полный ответ, пересмотри его и попробуй новый график.</p><p className={styles.note}>Два авторских графика. Нет AI-проверки текста или band. Работа хранится в открытой вкладке и исчезнет при обновлении страницы.</p></header>
    {phase==='start'&&<section className={styles.startCard}><h2>От графика к точному описанию</h2><ol><li>Выбери три главные особенности и напиши overview без образца.</li><li>Найди опору в данных и исправь неточный абзац.</li><li>Сравни с разбором, напиши и пересмотри полный ответ.</li><li>Повтори отбор и проверку на другом графике.</li></ol><button type="button" className={styles.primary} onClick={begin}>Начать с первого графика →</button></section>}
    {phase!=='start'&&<section className={styles.lesson} aria-labelledby="overview-stage-title"><div className={styles.lessonTop}><button type="button" onClick={()=>{setPhase('start');window.scrollTo({top:0});}}>← К началу</button><span>{round===0?'График 1 из 2':'Новый график 2 из 2'}</span></div><h2 id="overview-stage-title" tabIndex={-1}>{phase==='select'?'1. Выбери главное и напиши overview':phase==='evidence'?'2. Найди опору для утверждений':phase==='accuracy'?'3. Убери неточности':phase==='review'?'4. Сравни свой ход мысли':phase==='draft'?'5. Напиши полный ответ':phase==='revise'?'6. Пересмотри свой ответ':'Что получилось на двух графиках'}</h2>
      {phase!=='result'&&<div className={styles.workGrid}><div><Chart item={item}/></div><div className={styles.response}>
        {phase==='select'&&<><fieldset className={styles.claims}><legend>Выбери ровно три особенности, достойные overview</legend>{order.map((index)=><label key={index} className={selected.includes(index)?styles.selected:styles.choice}><input type="checkbox" checked={selected.includes(index)} onChange={()=>setSelected((previous)=>previous.includes(index)?previous.filter((value)=>value!==index):[...previous,index])}/><span lang="en">{item.claims[index].text}</span></label>)}</fieldset><p className={styles.note}>Выбрано {selected.length} из 3. Overview передаёт общую картину, а не каждую точку.</p><label htmlFor="own-overview">Твой overview: одно-два предложения на английском</label><textarea id="own-overview" value={overview} maxLength={1800} onChange={(event)=>setOverview(event.target.value)}/><button type="button" className={styles.primary} onClick={commitSelection}>Зафиксировать overview →</button></>}
        {phase==='evidence'&&<><h3>Твой overview зафиксирован</h3><p className={styles.saved} lang="en">{overview}</p><p>Проверь выбранные утверждения. Это проверка опоры для готовых утверждений; смысл твоего свободного текста ты сверишь сам после разбора.</p>{selected.map((index)=><div className={styles.evidenceRow} key={index}><p lang="en">{item.claims[index].text}</p><label htmlFor={`evidence-${index}`}>Опора для утверждения {selected.indexOf(index)+1}</label><select id={`evidence-${index}`} value={evidence[index]??''} onChange={(event)=>setEvidence((previous)=>updateChoice(previous,index,event.target.value))}><option value="">Выбери опору</option>{item.evidence.map((value,source)=><option value={source} key={value}>{value}</option>)}</select></div>)}<button type="button" className={styles.primary} onClick={commitEvidence}>Зафиксировать опоры →</button></>}
        {phase==='accuracy'&&<><p>В учебном абзаце три предложения. Проверь каждое по графику, затем перепиши абзац точнее.</p>{item.inaccurate.map((entry,index)=><div className={styles.evidenceRow} key={index}><p lang="en">{entry.text}</p><label htmlFor={`accuracy-${index}`}>Как оценить предложение {index+1}?</label><select id={`accuracy-${index}`} value={reasons[index]??''} onChange={(event)=>setReasons((previous)=>updateChoice(previous,index,event.target.value))}><option value="">Выбери оценку</option>{accuracyReasons.map((value,reason)=><option value={reason} key={value}>{value}</option>)}</select></div>)}<label htmlFor="data-correction">Твой исправленный абзац на английском</label><textarea id="data-correction" value={correction} maxLength={3000} onChange={(event)=>setCorrection(event.target.value)}/><button type="button" className={styles.primary} onClick={commitAccuracy}>Открыть разбор →</button></>}
        {phase==='review'&&(round===0?first:transfer)&&<>{report((round===0?first:transfer)!,item)}<button type="button" className={styles.primary} onClick={()=>{if(round===0){setDraft(first?.overview??'');advance('draft');}else advance('result');}}>{round===0?'Собрать полный ответ →':'Сравнить две попытки →'}</button></>}
        {phase==='draft'&&<><p>Собери связный ответ: введение, overview и два абзаца с выбранными сравнениями. Используй график и таблицу; не добавляй неизвестные причины.</p><label htmlFor="task1-draft">Полный черновик на английском</label><textarea id="task1-draft" className={styles.longDraft} value={draft} maxLength={10000} onChange={(event)=>setDraft(event.target.value)}/><p className={styles.note}>Примерно {countWords(draft)} слов. В IELTS Task 1 требуется минимум 150; здесь короткую учебную попытку можно сохранить без оценки.</p><button type="button" className={styles.primary} onClick={()=>{if(!draft.trim()){setError('Напиши черновик перед самопроверкой.');return;}setRevision(draft);advance('revise');}}>Перейти к самопроверке →</button></>}
        {phase==='revise'&&<><p>Проверь главное, порядок идей, слова для сравнений и грамматику. Выбери один аспект для правки и сохрани новую версию.</p><label htmlFor="revision-focus">На чём сосредоточишься?</label><select id="revision-focus" value={focus} onChange={(event)=>setFocus(event.target.value)}><option value="">Выбери аспект</option>{revisionFocus.map((value)=><option key={value}>{value}</option>)}</select><details><summary>Показать исходный черновик</summary><p className={styles.saved} lang="en">{draft}</p></details><label htmlFor="task1-revision">Твой пересмотренный ответ</label><textarea id="task1-revision" className={styles.longDraft} value={revision} maxLength={10000} onChange={(event)=>setRevision(event.target.value)}/><label className={styles.noChanges}><input type="checkbox" checked={noChanges} onChange={(event)=>setNoChanges(event.target.checked)}/>Я проверил выбранный аспект и решил сохранить текст без правок</label><button type="button" className={styles.primary} onClick={()=>{if(!focus||!revision.trim()){setError('Выбери аспект и заполни новую версию.');return;}if(revision.trim()===draft.trim()&&!noChanges){setError('Внеси правку или явно отметь, что решил оставить текст без изменений.');return;}startTransfer();}}>Сохранить и попробовать новый график →</button></>}
        {error&&<p className={styles.warning} role="alert">{error}</p>}
      </div></div>}
      {phase==='result'&&first&&transfer&&<><div className={styles.compare}><section><h3>Первый overview</h3><p lang="en">{first.overview}</p><p>Главные особенности: {first.selected.filter((index)=>overviewItems[0].claims[index].main).length} из 3.</p></section><section><h3>Overview нового графика</h3><p lang="en">{transfer.overview}</p><p>Главные особенности: {transfer.selected.filter((index)=>overviewItems[1].claims[index].main).length} из 3.</p></section></div><h3>Твой полный ответ по первому графику</h3><p>Аспект самопроверки: {focus}. {draft.trim()===revision.trim()?'Текст сохранён без изменений.':'Сохранена новая версия; её качество автоматически не оценивалось.'}</p><div className={styles.compare}><section><h3>До самопроверки · {countWords(draft)} слов</h3><p className={styles.saved} lang="en">{draft}</p></section><section><h3>После самопроверки · {countWords(revision)} слов</h3><p className={styles.saved} lang="en">{revision}</p></section></div><details className={styles.model}><summary>Один пример полного ответа по первому графику</summary><p className={styles.saved} lang="en">{overviewItems[0].modelResponse}</p><p className={styles.note}>Учебный пример без присвоенного band. Другие точные формулировки и группировки тоже допустимы.</p></details><p className={styles.note}>Выборы и опоры сравниваются с авторской разметкой. Тексты overview, исправления и полного ответа не получили автоматическую оценку. Два графика не доказывают устойчивый навык или рост балла.</p><button type="button" className={styles.primary} onClick={begin}>Начать заново →</button></>}
    </section>}
    <p className={styles.source}>Требования формата: <a href="https://ielts.org/take-a-test/test-types/ielts-academic-test/ielts-academic-format-writing" target="_blank" rel="noopener noreferrer">официальный IELTS Academic Writing ↗</a></p>
  </main>;
}
